### ISSUE TITLE
Improve search function

### ISSUE THREAD

**Issue by sakshi2912** [sakshi2912/phonebook#14]
The current implementation searches for a contact by the Name of the person.

Give the user a choice to search by Phone number or email ID.

**Comment by Prajwal2204** [comment]
hey @sakshi2912, I would like to work on this!

**Comment by sakshi2912** [comment]
> hey @sakshi2912, I would like to work on this!

Sure, I've assigned you to the issue.

**Comment by anushkadeshpande** [comment]
I would like to give it a try

**Comment by sakshi2912** [comment]
> I would like to give it a try

Yes, Go ahead!

**Comment by shreya-panale** [comment]
Hey, I would like to try this

**Comment by sakshi2912** [comment]
> Hey, I would like to try this

Go ahead!

**Comment by abhishek-mishra17** [comment]
hey @sakshi2912  I would like to work on this
