### ISSUE TITLE
Improve modify contact

### ISSUE THREAD

**Issue by sakshi2912** [sakshi2912/phonebook#16]
Current implementation requires the user to enter all the details all over again.
Instead, let the user be given a choice to modify any particular field of his/her choice, and not re-enter all the fields.

**Comment by Radheshyam23** [comment]
Hey, Can i try this?

**Comment by sakshi2912** [comment]
> Hey, Can i try this?

Sure, I've assigned you to the issue.

**Comment by Ares358** [comment]
I'd like to give it a try as well, If possible.

**Comment by sakshi2912** [comment]
> I'd like to give it a try as well, If possible.

Yup, go ahead.

**Comment by abhishek-mishra17** [comment]
hey  @sakshi2912  I would like to work on this

**Comment by sakshi2912** [comment]
> hey @sakshi2912 I would like to work on this

Go ahead
