### ISSUE TITLE
Allow multiple mobile numbers under each name

### ISSUE THREAD

**Issue by sakshi2912** [sakshi2912/phonebook#17]
A user can have multiple phone numbers associated with him.
Add a functionality to allow the addition of more than one number under same name.

In case a record with that name already exists, ask the user if he/she wishes to merge both the contacts or create a new one.

If there exists a contact named "abc" as :

Name : abc
Phone : 1231231231
Email : acb@def.com
Address : abcd
Age: 12

When the user adds another contact with the same name "abc", the new number should be stored as:

Name : abc
Phone : 1231231231/9999999999
Email : acb@def.com
Address : abcd
Age: 12

**Comment by shreya-panale** [comment]
Hey @sakshi2912 , I would like to work on this!

**Comment by sakshi2912** [comment]
> Hey @sakshi2912 , I would like to work on this!

Sure , I've assigned you to this issue.

**Comment by RakshithRAcharya** [comment]
Isn't this already done...Can we do it again??

**Comment by sakshi2912** [comment]
> Isn't this already done...Can we do it again??

You can do it
