### ISSUE TITLE
Change the input method for name and address fields

### ISSUE THREAD

**Issue by shreya-panale** [sakshi2912/phonebook#20]
Currently, only the characters before space are taken into the consideration.
For example, only the first name is saved for the name field

**Comment by Prajwal2204** [comment]
hey @ShreyaPanale, can I work on this?

**Comment by sakshi2912** [comment]
> hey @ShreyaPanale, can I work on this?

@Prajwal2204 , Both of you can work on it

**Comment by sakshi2912** [comment]
!bounty 10
