### ISSUE TITLE
Check for Email

### ISSUE THREAD

**Issue by sakshi2912** [sakshi2912/phonebook#9]
Add a function which would check for a valid email address.

**Comment by KeshriAyushi22** [comment]
you can assign this to me. @sakshi2912 would love to contribute

**Comment by sakshi2912** [comment]
> you can assign this to me. @sakshi2912 would love to contribute

Sure, go ahead

**Comment by psymbio** [comment]
When you say valid you just mean that the function does string comparisons to check whether the email is properly formatted, right?

If so can I be assigned this issue.

**Comment by sakshi2912** [comment]
> When you say valid you just mean that the function does string comparisons to check whether the email is properly formatted, right?
> 
> If so can I be assigned this issue.

Yes, and an empty string for email should also be accepted.

**Comment by psymbio** [comment]
> Yes, and an empty string for email should also be accepted.

Okie-doke.
I'll try my best.

**Comment by anirudhRowjee** [comment]
Are PRs still being accepted for this issue?
edit: was considering using the POSIX `regex.h` library for easier validation.

**Comment by sakshi2912** [comment]
> Are PRs still being accepted for this issue?
> edit: was considering using the POSIX `regex.h` library for easier validation.

I'll reopen the issue, you can go ahead and work on it!

**Comment by anirudhRowjee** [comment]
Thank you

**Comment by abhishek-mishra17** [comment]
hey @sakshi2912 can i work on this

**Comment by sakshi2912** [comment]
> hey @sakshi2912 can i work on this

Sure, go ahead

**Comment by anirudhRowjee** [comment]
Hi, I had a doubt

In terms of platform compatibility, what are we looking for? It appears that we need to install the regex library in question separately on windows to be able to build this project, if the regex validator were added. I have no problem implementing it, but we might lose out on cross-platform compatiblity if it were to be implemented. 

I leave the choice to the maintainers.

**Comment by sakshi2912** [comment]
> Hi, I had a doubt
> 
> In terms of platform compatibility, what are we looking for? It appears that we need to install the regex library in question separately on windows to be able to build this project, if the regex validator were added. I have no problem implementing it, but we might lose out on cross-platform compatiblity if it were to be implemented.
> 
> I leave the choice to the maintainers.

You can consider implementing it on Linux for now.
You can bring up another issue for the platform compatibility.
